import React from "react";
import HeaderMain from "./HomePage/HeaderMain";
import Hero from "./HomePage/Hero";
import Banner from "./HomePage/Banner";
import Product from "./HomePage/Product";
import Deal from "./HomePage/Deal";
import PopularProducts from "./HomePage/PopularProducts";
import Client from "./HomePage/Client";
import WebSpeciails from "./HomePage/WebSpeciails";
import Footer from "./HomePage/Footer";
import Arrivals from "./HomePage/Arrivals";
import Offer from "./HomePage/Offer";
import Navbar from "./components/Navbar/Navbar";
import HeroBannerSlider from "./components/banner/HeroBannerSlider";
// import HeroSection from "./components/utils/HeroSection";

export const metadata = {
  title: "Online King",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico"],
  },
};

const page = () => {
  return (
    <>
      {/* <HeaderMain /> */}
      <Navbar />
      <Hero />
      <Banner />
      {/* <HeroSection /> */}
      {/* <HeroBannerSlider /> */}
      {/* <Offer /> */}
      <div className="md:px-8 px-2">
        <Arrivals />
        <Product />
        <Deal />
        <PopularProducts />
        {/* <Client /> */}
        <WebSpeciails />
      </div>
      <Footer />
    </>
  );
};

export default page;
